name: Deploy to S3
on:
 push:
   branches:
     - main
jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout Repository
     uses: actions/checkout@v3
   - name: Setup Python
     uses: actions/setup-python@v3
     with:
       python-version: 3.9
   - name: Run Python Script
     run: python factorial.py
   - name: Setup Terraform
     uses: hashicorp/setup-terraform@v1
   - name: Terraform Init
     run: terraform init
  manual_approval:
   runs-on: ubuntu-latest
   needs: deploy_to_s3
   steps:
     - name: Wait for manual approval
       uses: peaceiris/actions-wait-for-approval@v2
     - name: Set up Terraform
       uses: hashicorp/setup-terraform@v1
     - name: Terraform Apply (Manual Approval)
       run: terraform apply
     env:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}