name: Deploy to S3
on:
  push:
    branches:
      - main
  workflow_dispatch: # for manual triggering

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Run Python Script
      run: python factorial.py
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform Init
      run: terraform init
    - name: Terraform Plan
      run: terraform plan -out=plan.out
    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v2
      with:
        name: terraform-plan
        path: plan.out

  review:
    needs: plan
    runs-on: ubuntu-latest
    steps:
    - name: Download Terraform Plan
      uses: actions/download-artifact@v2
      with:
        name: terraform-plan
    - name: Review and Approve
      run: echo "Review the terraform plan here and approve it manually"
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform Apply
      run: |
        read -p "Do you want to apply the plan (yes/no)? " answer
        if [ "$answer" == "yes" ]
        then
          terraform apply -auto-approve plan.out
        fi
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
