name: Deploy to S3
on:
 push:
   branches:
     - main
 workflow_dispatch:
   inputs:
     manual-apply:
       description: 'Manually trigger Terraform Apply'
       default: 'false'
jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout Repository
       uses: actions/checkout@v3
     - name: Setup Python
       uses: actions/setup-python@v3
       with:
         python-version: 3.9
     - name: Run Python Script
       run: python factorial.py
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v1
     - name: Terraform Init
       run: terraform init
     - name: Terraform Plan
       run: terraform plan -out=tfplan
 terraform-apply:
   runs-on: ubuntu-latest
   needs: deploy
   if: github.event_name == 'workflow_run' && github.event.workflow_run.event == 'workflow_run.requested' && matrix.manual-apply == 'true'
   strategy:
     matrix:
       manual-apply: [true, false]
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Terraform Apply
       run: terraform apply tfplan
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 manual-apply-approval:
   runs-on: ubuntu-latest
   needs: terraform-apply
   if: needs.terraform-apply.result == 'success' && github.event_name == 'workflow_run' && github.event.workflow_run.event == 'workflow_run.requested'
   steps:
     - name: Manual Apply Approval
       id: manual-apply-approval
       run: echo "Approve Terraform Apply"