name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan -out=plan.tfplan

      - name: Save plan to artifact
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: plan.tfplan

  review:
    runs-on: ubuntu-latest

    steps:
      - name: Download plan artifact
        uses: actions/download-artifact@v2
        with:
          name: terraform-plan

      - name: Review plan
        run: terraform show -json plan.tfplan > plan.json

      - name: Approve plan
        run: echo "Approved" > approval.txt

  apply:
    needs: review
    runs-on: ubuntu-latest

    steps:
      - name: Download approved plan
        uses: actions/download-artifact@v2
        with:
          name: terraform-plan

      - name: Terraform apply
        run: terraform apply -auto-approve -input=false plan.tfplan
