name: Deploy Python file to S3
 
on:
  workflow_dispatch: # enable manual trigger
    inputs:
      apply_terraform:
        description: 'Apply Terraform (true or false)' # ask for user input
        required: true
        default: 'false'
  push:
    branches:
      - main
 
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
 
      - name: Terraform Init
        run: terraform init
 
      - name: Terraform Plan
        run: | 
          upload=$( terraform plan -out=plan.out)
          echo "TERRAFORM_PLAN=$upload" > terraform_plan.txt
      - name: Upload Plan
        uses: actions/upload-artifact@v2
        with:
          name: plan
          path: terraform_plan.txt
 
  apply:
    needs: plan
    runs-on: ubuntu-latest
     
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - name: Download Plan
        uses: actions/download-artifact@v2
        with:
          name: plan
       
      - name: Plan Output
        run: |
          output=$(cat terraform_plan.txt)
          echo "Plan output : $output"
      
      - name: Output contents
        run: ls -R
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
 
      - name: Terraform Apply
        if: ${{ github.event.inputs.apply_terraform == 'true' }} # check the user input
        run: terraform apply plan.out # apply the saved plan