name: Deploy to S3
on:
 push:
   branches:
     - main
jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout Repository
     uses: actions/checkout@v3
   - name: Setup Python
     uses: actions/setup-python@v3
     with:
       python-version: 3.9
   - name: Run Python Script
     run: python factorial.py
   - name: Setup Terraform
     uses: hashicorp/setup-terraform@v1
   - name: Terraform Init
     run: terraform init
  - name: Terraform Plan
     run: terraform plan -out=tfplan
 terraform-apply:
   runs-on: ubuntu-latest
   needs: deploy
   if: github.event_name == 'workflow_run' && github.event.workflow_run.event == 'workflow_run.requested'
   steps:
   - name: Checkout code
     uses: actions/checkout@v2
   - name: Terraform Apply
     run: terraform apply tfplan
     env:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}