name: Deploy Python file to S3

on:
  workflow_dispatch:
    inputs:
      apply_terraform:
        description: 'Apply Terraform (true or false)'
        required: true
        default: 'false'
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=plan.out

      - name: Archive Terraform plan
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: plan.out

  review:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Download Terraform plan
        uses: actions/download-artifact@v2
        with:
          name: terraform-plan
          path: .

      # Additional steps for reviewing the plan, if needed
      # ...

      - name: Apply Terraform changes
        if: ${{ github.event.inputs.apply_terraform == 'true' }}
        run: terraform apply plan.out
